### ISSUE TITLE
Package license is incorrect.

### ISSUE THREAD

**Issue by Zimmi48** [conda-forge/coq-feedstock#2]
Issue: the license of Coq is LGPL 2.1, and not the MIT license as indicated here.

---

BTW, hi @slel and @isuruf! Seems like the right time to report such an issue since you are both in Cernay working on packaging matters ;-) Sorry I couldn't come.

I discovered the existence of this conda package through the Gitter channel of the coq_jupyter kernel (https://gitter.im/coq_jupyter/community). A user had a problem there with the Conda packaged Coq, but it seriously lacks sufficient info to debug it.

Another quick remark in passing: we are listing a number of packages in our README: https://github.com/coq/coq#installation. For this, we are using the badges provided by Repology (https://repology.org/project/coq/versions). Unfortunately, it seems that conda-forge is not listed in there. If it was, we could add a new badge...

**Comment by slel** [comment]
Thanks. See https://github.com/conda-forge/coq-feedstock/pull/3

**Comment by slel** [comment]
Regarding conda-forge and repology, it seems to be a matter of
conda-forge providing metadata in a way that repology can use,
the issue is being discussed and it should happen at some point.

**Comment by isuruf** [comment]
Btw, you can use https://img.shields.io/conda/vn/conda-forge/coq.svg?label=%22Conda%20package%22 as a badge for conda.
